# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='race.Driver'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='race date'),
        ),
    ]
